# Generated by Django 5.2.7 on 2025-10-27 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Curso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_curso", models.CharField(max_length=200)),
                ("datetime_added", models.DateTimeField(auto_now_add=True)),
                (
                    "code",
                    models.CharField(
                        default="92430dcc12294b3cb060167bb9ea4b33",
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("comision", models.IntegerField(unique=True)),
            ],
        ),
    ]
