# Generated by Django 5.2.7 on 2025-10-27 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cursos", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="curso",
            options={
                "permissions": [("ver_cursos_detail", "Puede ver el detalle del curso")]
            },
        ),
        migrations.AlterField(
            model_name="curso",
            name="code",
            field=models.CharField(
                default="b87fc1a391104e6abaa81f3780fe1647", max_length=32, unique=True
            ),
        ),
    ]
