# Generated by Django 5.2.7 on 2025-10-27 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cursos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Examenes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nota", models.FloatField()),
                ("asignatura", models.CharField(max_length=30)),
                ("nombre_de_estudiante", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Estudiante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("apellido", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("nro_legajo", models.IntegerField(unique=True)),
                ("fecha_de_creacion", models.DateTimeField(auto_now_add=True)),
                ("fehca_de_nacimiento", models.DateField(null=True)),
                (
                    "curso",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="estudiantes",
                        to="cursos.curso",
                    ),
                ),
            ],
        ),
    ]
